teste = input('Testando a função is, digite algo: ')
print(f'O tipo dele é: {type(teste)}')
print(f'É alfanumérico? {teste.isalnum()}')
print(f'É alfabético? {teste.isalpha()}')
print(f'É decimal? {teste.isdecimal()}')
print(f'É um dígito? {teste.isdigit()}')
print(f'É numérico? {teste.isnumeric()}')
print(f'É printável? {teste.isprintable()}')
print(f'É um título? {teste.istitle()}')
print(f'É maiúsculo? {teste.isupper()}')
print(f'É minúsculo? {teste.islower()}')
print(f'É um espaço? {teste.isspace()}')
print(f'É identificador? {teste.isidentifier()}')